export const IconNames = {
    ANGLE_DOWN: 'angle-down',
    ANGLE_LEFT: 'angle-left',
    ANGLE_RIGHT: 'angle-right',
    ANGLE_UP: 'angle-up',
    ARROW_ALT_CIRCLE_DOWN: 'arrow-alt-circle-down',
    ARROW_ALT_CIRCLE_LEFT: 'arrow-alt-circle-left',
    ARROW_ALT_CIRCLE_RIGHT: 'arrow-alt-circle-right',
    ARROW_ALT_CIRCLE_UP: 'arrow-alt-circle-up',
    BACKSPACE: 'backspace',
    BAN: 'ban',
    CALENDAR_ALT: 'calendar-alt',
    CLOSE: 'times',
    PHONE: 'phone',
    PLUS: 'plus',
    PLUS_SQUARE: 'plus-square',
    ROCKET: 'rocket',
    SYNC: 'sync',
    SYNC_ALT: 'sync-alt',
    TRASH: 'trash',
    TRASH_ALT: 'trash-alt',
    ERROR: 'exclamation-circle',
    WARNING: 'exclamation-triangle',
    SUCCESS: 'check-circle'
};
