const NAMESPACE_API = 'api';
const LOCALIZATION_SERVICE = 'localization';

export const API_URL = {
    GET_ALL_DICTIONARY: `/${NAMESPACE_API}/${LOCALIZATION_SERVICE}/dictionary`,
    GET_LABELS: `/${NAMESPACE_API}/${LOCALIZATION_SERVICE}/labels`,
    GET_LOCALES: `/${NAMESPACE_API}/${LOCALIZATION_SERVICE}/locales`
};
